import type { OfflineDemoPayload } from "@/lib/offline-demo";

/** Synthetic session id when co-pilot runs without the Python API (browser demo). */
export const OFFLINE_CHAT_SESSION_ID = "offline-browser-demo";

export type OfflineChatPayload = { answer: string; suggestions: string[] };

function overviewAnswer(payload: OfflineDemoPayload | null): string {
  if (!payload?.audit?.length) {
    return (
      "You're viewing the dashboard **without** a live Agentiva API. To use the full co-pilot against your audit log, run **`agentiva serve --port 8000`** and open the dashboard locally (or set **`AGENTIVA_API_URL`** on your Vercel project).\n\n" +
      "On the welcome page, click **Run demo with sample data** to load browser-only sample actions — then you can ask what was blocked or for a session summary here."
    );
  }
  const { report, audit } = payload;
  const byDec = Object.entries(report.by_decision)
    .map(([k, v]) => `**${k}** × ${v}`)
    .join(", ");
  return (
    `**Session overview** (browser sample data)\n\n` +
    `- Total actions: **${report.total_actions}**\n` +
    `- Decisions: ${byDec || "—"}\n` +
    `- Average risk: **${report.avg_risk_score.toFixed(2)}**\n` +
    `- Demo agent **demo-agent-1** with **${audit.length}** sample intercepts\n\n` +
    `This is **offline** mode — answers are generated from the sample data only. Connect the API for full chat history and LLM-powered replies (optional **OPENROUTER_API_KEY** on the server).`
  );
}

/**
 * Deterministic co-pilot replies when `POST /api/v1/chat/sessions` cannot reach the backend.
 */
export function offlineCoPilotReply(message: string, payload: OfflineDemoPayload | null): OfflineChatPayload {
  const q = message.trim().toLowerCase();
  const audit = payload?.audit ?? [];

  if (!q) {
    return { answer: overviewAnswer(payload), suggestions: ["What was blocked?", "Explain shadow mode"] };
  }

  if (/^(hi|hello|hey|howdy)\b|^good (morning|afternoon|evening)/.test(q)) {
    return {
      answer:
        `Hi — I'm the **Security co-pilot** in **offline demo** mode.\n\n` +
        (audit.length ? overviewAnswer(payload) : "Load sample data from the welcome screen, then ask about blocks, risk, or shadow mode."),
      suggestions: ["Session overview", "What was blocked?"],
    };
  }

  if (q.includes("overview") || q.includes("summary") || q.includes("session")) {
    return {
      answer: overviewAnswer(payload),
      suggestions: ["What was blocked?", "Which tools ran?"],
    };
  }

  if (q.includes("block") || q.includes("blocked")) {
    if (!audit.length) {
      return {
        answer: overviewAnswer(null),
        suggestions: ["Session overview"],
      };
    }
    const blocks = audit.filter((a) => a.decision === "block");
    const lines = blocks.map(
      (b) =>
        `- **${b.tool_name}** — risk **${b.risk_score.toFixed(2)}** (${JSON.stringify(b.arguments).slice(0, 80)}…)`,
    );
    return {
      answer:
        `**Blocked actions** in this sample (${blocks.length}):\n\n` +
        (lines.length ? lines.join("\n") : "No blocks in the current sample.") +
        `\n\nIn **live** mode with the API, blocks enforce policy before side effects run.`,
      suggestions: ["Session overview", "Explain shadow mode"],
    };
  }

  if (q.includes("shadow")) {
    return {
      answer:
        "**Shadow mode** observes and logs risky or policy-touched actions **without** blocking side effects. In this sample, decisions still show **block** / **allow** / **shadow** so you can see how the feed looks.\n\nSwitch to **Live** in Security settings when the API is connected to enforce blocks automatically.",
      suggestions: ["What was blocked?", "Session overview"],
    };
  }

  if (q.includes("risk") || q.includes("threshold")) {
    return {
      answer:
        "The sample run includes scores from about **0.14** (low) to **0.97** (high). **Risk threshold** (e.g. **0.70**) is used in **live** mode with the real API: allows at or above the threshold can be treated as blocks depending on policy.\n\nAdjust it in **Security settings** when **`agentiva serve`** is running.",
      suggestions: ["Session overview", "What was blocked?"],
    };
  }

  if (q.includes("export") || q.includes("compliance") || q.includes("hipaa") || q.includes("soc") || q.includes("pci")) {
    return {
      answer:
        "Compliance **JSON / PDF** exports are generated by the **Python API** from your persisted audit log. They are not available in **browser-only** demo mode.\n\nRun the stack locally or deploy the API and set **`AGENTIVA_API_URL`** on the dashboard host.",
      suggestions: ["Session overview"],
    };
  }

  if (q.includes("tool") || q.includes("action")) {
    if (!audit.length) {
      return { answer: overviewAnswer(null), suggestions: ["Session overview"] };
    }
    const tools = [...new Set(audit.map((a) => a.tool_name))];
    return {
      answer: `**Tools** seen in this sample: ${tools.map((t) => `**${t}**`).join(", ")}.`,
      suggestions: ["What was blocked?", "Session overview"],
    };
  }

  return {
    answer:
      overviewAnswer(payload) +
      `\n\nTry asking: **what was blocked?**, **session overview**, **shadow mode**, or **risk threshold**.`,
    suggestions: ["Session overview", "What was blocked?", "Explain shadow mode"],
  };
}
