"""Shared PDF helpers for compliance reports (ReportLab)."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List

from reportlab.lib.units import inch
from reportlab.platypus import PageBreak, Paragraph, Spacer


def esc(text: str) -> str:
    return (
        (text or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def action_to_row(a: Any) -> Dict[str, Any]:
    ts = a.timestamp
    if hasattr(ts, "isoformat"):
        ts_s = ts.isoformat()
    else:
        ts_s = str(ts)
    return {
        "id": a.id,
        "timestamp": ts_s,
        "tool_name": a.tool_name,
        "arguments": a.arguments or {},
        "agent_id": a.agent_id,
        "decision": a.decision,
        "risk_score": float(a.risk_score or 0),
        "mode": a.mode,
    }


def summarize_actions(rows: List[Dict[str, Any]]) -> Dict[str, Any]:
    n = len(rows)
    if n == 0:
        return {
            "total": 0,
            "blocked": 0,
            "shadowed": 0,
            "allowed": 0,
            "block_rate": 0.0,
            "avg_risk": 0.0,
            "high_risk": 0,
            "agents": set(),
        }
    blocked = sum(1 for r in rows if r["decision"] == "block")
    shadowed = sum(1 for r in rows if r["decision"] == "shadow")
    allowed = sum(1 for r in rows if r["decision"] in ("allow", "approve", "live"))
    risks = [r["risk_score"] for r in rows]
    return {
        "total": n,
        "blocked": blocked,
        "shadowed": shadowed,
        "allowed": allowed,
        "block_rate": blocked / n,
        "avg_risk": sum(risks) / n,
        "high_risk": sum(1 for x in risks if x > 0.7),
        "agents": {r["agent_id"] for r in rows},
    }


def build_cover(
    story: list,
    styles: Any,
    *,
    title: str,
    subtitle: str,
    company: str,
    period_start: datetime,
    period_end: datetime,
    generated_by: str = "Agentiva",
) -> None:
    story.append(Spacer(1, 1.2 * inch))
    story.append(Paragraph(esc(title), styles["Title"]))
    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph(esc(subtitle), styles["Heading2"]))
    story.append(Spacer(1, 0.4 * inch))
    story.append(Paragraph(esc(f"Organization: {company}"), styles["Normal"]))
    story.append(
        Paragraph(
            esc(
                f"Reporting period: {period_start.isoformat()} — {period_end.isoformat()}"
            ),
            styles["Normal"],
        )
    )
    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph(esc(f"Generated by {generated_by}"), styles["Normal"]))
    story.append(PageBreak())
